#cloud-config
users:
  - name: philip
    uid: 1000
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: podman
    uid: 1001
    shell: /bin/bash

package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - fail2ban
  - ufw
  - unattended-upgrades
  - podman
  - gettext-base
  - pwgen
  - systemd-container
  - htop
  - gh

write_files:
  - path: /etc/ssh/sshd_config.d/ssh-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      Port 2222
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      MaxAuthTries 2
      AllowTcpForwarding yes
      X11Forwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys
      AllowUsers philip
  - path: /etc/sysctl.d/99-podman-ports.conf
    content: |
      net.ipv4.ip_unprivileged_port_start=80

runcmd:
  - mkdir -p /home/philip/.ssh
  - cp /root/.ssh/authorized_keys /home/philip/.ssh/authorized_keys
  - chown -R philip:philip /home/philip/.ssh
  - chmod 700 /home/philip/.ssh
  - chmod 600 /home/philip/.ssh/authorized_keys
  - dpkg-reconfigure -f noninteractive unattended-upgrades
  - printf "[sshd]\nenabled = true\nport = 2222\nbanaction = iptables-multiport\n" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - ufw allow 2222/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw --force enable
  - sysctl --system
  - loginctl enable-linger podman
  - reboot