FROM docker.io/library/postgres:18-alpine

RUN apk add --no-cache --virtual .build-deps \
    build-base \
    git \
    clang21 \
    llvm21-dev \
    && git clone --branch v0.8.6 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && cd .. \
    && rm -rf pgvector \
    && apk del .build-deps